name = "Devfest Toulouse Theme"
license = "MIT"
licenselink = "https://github.com/cicm-la/cicm-theme-hugo/LICENSE"
description = "A theme for a conference website. Created for CICM AL 2023"
homepage = "https://github.com/cicm-la/cicm-theme-hugo"
tags = ["conference", "DevFest"]
features =  ["conference", "responsive", "l10n", "google-analytics"]
min_version = "0.50"

[author]
  name = "CICM LA"
  homepage = "//github.com/cicm-la"
